api:
  url: 'http://localhost:4000/api'
  token: '' # 실제 배포 시 설정 필요

inventory:
  title: '&6MuffinCraft Inventory'
  rows: 6 # 인벤토리 행 수 (1행 = 9슬롯)

currency:
  enable: true
  symbol: '₩'  # 화폐 기호
  default_balance: 0

# 리소스팩 설정
resourcepack:
  # 리소스팩 다운로드 URL (NestJS 백엔드에서 호스팅)
  # 백엔드 서버 URL + API prefix + 리소스팩 엔드포인트
  url: "http://localhost:4000/api/muffincraft/resourcepack/download"
  
  # 리소스팩 파일의 SHA-1 해시 (무결성 검증용)
  # 현재 생성된 파일의 해시: 537B9F97E860811A8D102DCC449463063F8A2A90
  sha1: "537B9F97E860811A8D102DCC449463063F8A2A90"
  
  # 리소스팩 적용을 필수로 할지 여부
  required: true
  
  # 리소스팩 적용 실패 시 메시지
  failure_message: "§c리소스팩 적용에 실패했습니다. 게임이 정상적으로 표시되지 않을 수 있습니다."

# 커스텀 아이템 설정
custom_items:
  muffin:
    # 베이스 아이템 (Minecraft 기본 아이템)
    base_material: "BREAD"
    
    # CustomModelData 값 (리소스팩의 모델과 연동)
    custom_model_data: 1001
    
    # 아이템 이름
    display_name: "§6머핀"
    
    # 아이템 설명
    lore:
      - "§e머핀크래프트의 공식 화폐"
      - "§7달콤하고 맛있는 머핀!"
      - "§a우클릭하여 사용"
    
    # 사용 효과
    effects:
      health: 4.0      # 체력 회복량 (하트 2개)
      food: 6          # 배고픔 회복량
      saturation: 8.0  # 포화도 회복량

# 창고 시스템 설정
warehouse:
  # 창고 GUI 크기 (9의 배수, 최대 54)
  gui_size: 54
  
  # 창고 GUI 제목
  gui_title: "§6MuffinCraft 외부 창고"
  
  # 최대 출금 수량 (한 번에)
  max_withdraw: 2304  # 36스택

# 메시지 설정
messages:
  # 접속 시 환영 메시지
  welcome: "§aMuffinCraft에 오신 것을 환영합니다!"
  
  # 리소스팩 관련 메시지
  resourcepack:
    downloading: "§aMuffinCraft 리소스팩을 다운로드 중입니다..."
    success: "§a리소스팩이 성공적으로 적용되었습니다!"
    required: "§c리소스팩이 필요합니다! 게임을 정상적으로 즐기려면 리소스팩을 적용해주세요."
    failed: "§c리소스팩 다운로드에 실패했습니다. 인터넷 연결을 확인하거나 관리자에게 문의해주세요."
