name: MuffinCraft
version: '${version}'
main: com.snowmuffin.muffincraft.MuffinCraft
api-version: '1.21'
commands:
  inventory:
    description: 커스텀 인벤토리를 엽니다
    usage: /<command>
    aliases: [inv]

