name: MuffinCraft
version: '1.0.0'
main: com.muffincraft.plugin.MuffinCraftPlugin
api-version: '1.20'
authors: [GameHub]
description: GameHub의 MuffinCraft 플러그인
website: https://gamehub.example.com

commands:
  muffincraft:
    description: MuffinCraft 플러그인의 메인 명령어
    usage: /<command> [reload|sync|inventory|balance]
    aliases: [mc]
    permission: muffincraft.use
  inventory:
    description: "[DEPRECATED] MuffinCraft 온라인 인벤토리를 엽니다"
    usage: /<command>
    permission: muffincraft.inventory
  warehouse:
    description: MuffinCraft 외부 창고를 엽니다
    usage: /<command> [list|deposit <quantity>|withdraw <itemId> <quantity>|help]
    aliases: [wh, 창고]
    permission: muffincraft.warehouse
  balance:
    description: MuffinCraft 재화 잔액을 확인합니다
    usage: /<command> [send <player> <amount>]
    permission: muffincraft.balance
  muffin:
    description: 머핀 아이템 관련 명령어
    usage: /<command> [give <amount>|help]
    aliases: [머핀]
    permission: muffincraft.muffin

permissions:
  muffincraft.*:
    description: MuffinCraft의 모든 권한을 부여합니다
    children:
      muffincraft.use: true
      muffincraft.admin: true
      muffincraft.inventory: true
      muffincraft.warehouse: true
      muffincraft.balance: true
      muffincraft.muffin: true
      muffincraft.admin.give: true
  muffincraft.use:
    description: MuffinCraft 플러그인의 기본 사용 권한
    default: true
  muffincraft.admin:
    description: MuffinCraft 플러그인의 관리자 권한
    default: op
  muffincraft.inventory:
    description: "[DEPRECATED] 온라인 인벤토리 사용 권한"
    default: true
  muffincraft.warehouse:
    description: 외부 창고 사용 권한
    default: true
  muffincraft.balance:
    description: 재화 시스템 사용 권한
    default: true
  muffincraft.muffin:
    description: 머핀 아이템 기본 사용 권한
    default: true
  muffincraft.admin.give:
    description: 머핀 아이템 지급 권한 (관리자 전용)
    default: op

api:
  url: http://localhost:3000
  token: '' # 실제 배포 시 설정 필요
